<!DOCTYPE html>
<html>
<head>
<title>Sitio Mapa1</title>
    <link href="http://netdna.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css" rel="stylesheet">
    <link href="/vendor/kartik-v/bootstrap-fileinput/css/fileinput.min.css" media="all" rel="stylesheet" type="text/css" />
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
    <script src="/vendor/kartik-v/bootstrap-fileinput/js/fileinput.min.js" type="text/javascript"></script>
    <!-- optionally if you need translation for your language then include
        locale file as mentioned below -->
    <script src="/vendor/kartik-v/bootstrap-fileinput/js/fileinput_locale_es.js"></script>


    <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=true"></script>
    <script type="text/javascript" src="/Assets/js/gmaps.js"></script>
    <link rel="stylesheet" type="text/css" href="/Assets/css/examples.css" />
    <link rel="stylesheet" type="text/css" href="/Assets/css/styles.css" />
</head>
<body>

<div class="horizontal-menu">
<ul>
    <li><a href="/">Home</a></li>
    <li><a href="/user/register">Registro</a></li>
    <li>
        <?php if (isset($_SESSION['id'])) { ?>
            <a href="/logout">Logout</a>
        <?php } else { ?>
            <a href="/login">Login</a>
        <?php }?>
    </li>

    <?php if (isset($_SESSION['id'])) { ?>
    <li>
            <a href="/panel">Panel</a>
    </li>
    <?php }?>
</ul>
</div>


<?php
// Aqui se renderiza el contenido del template .phtml
echo $content;
?>

<?php
    include 'Views/Static/HelpBox.phtml';

?>

<hr>
<pre>
<?php
var_dump($_SESSION);
?>
    </pre>
</body>
</html>
