
<script type="text/javascript">
    var map;
    var gMarkers = [];
    gMarkers['static'] = [];
    gMarkers['user'] = [];

    $(document).ready(function(){
        map = new GMaps({
            div: '#map',
            lat: -34.603978,
            lng: -58.386560,
            zoom: 13
        });

        /* ---Geolocation--- */
        GMaps.geolocate({
            success: function(position) {
                map.setCenter(position.coords.latitude, position.coords.longitude);
            },
            error: function(error) {
                //alert('Geolocation failed: '+error.message);
            },
            not_supported: function() {
                //alert("Your browser does not support geolocation");
            },
            always: function() {
                //alert("Done!");
            }
        })
        /* ---Geolocation--- */

        var viewTemplate = $('#view_marker_template').text();

<?php
foreach ($allLands as $land):
    if (empty($land->latitude) || empty($land->latitude)) {
        continue;
    }
?>
    var viewContent = viewTemplate.replace(/{{id}}/g, <?php echo $land->id; ?>);

        gMarkers['static'].push({
            lat: <?php echo $land->latitude; ?>,
            lng: <?php echo $land->longitude; ?>,
            title: "<?php echo $land->title; ?>",
            infoWindow: {
                content : viewContent
            }
        });

<?php endforeach; ?>

    map.addMarkers(gMarkers['static']);

        GMaps.on('marker_added', map, function(marker) {
            $('#markers-with-index').append('<li><a href="#" class="pan-to-marker" data-marker-index="' + map.markers.indexOf(marker) + '">' + marker.title + '</a></li>');

            $('#markers-with-coordinates').append('<li><a href="#" class="pan-to-marker" data-marker-lat="' + marker.getPosition().lat() + '" data-marker-lng="' + marker.getPosition().lng() + '">' + marker.title + '</a></li>');
        });

        GMaps.on('click', map.map, function(event) {
            var index = map.markers.length;
            var lat = event.latLng.lat();
            var lng = event.latLng.lng();

            var template = $('#edit_marker_template').text();

            var content = template.replace(/{{index}}/g, index).replace(/{{lat}}/g, lat).replace(/{{lng}}/g, lng);

            map.removeMarker(gMarkers['user']);

            gMarkers['user'] = map.addMarker({
                lat: lat,
                lng: lng,
                icon: "/Assets/images/map-marker-hi.png",
                title: 'Marker #' + index,
                infoWindow: {
                    content : content
                }
            });
        });
    });


</script>

<div id="map"></div>


<script type="text/html" id="edit_marker_template">
    <h4><a href="/land/create?lat={{lat}}&lng={{lng}}">Agregar un terreno aqui</a></h4>
</script>

<script type="text/html" id="view_marker_template">
    <h4><a href="/land/view/{{id}}">Ver</a></h4>
</script>
