CREATE TABLE lands
(
  id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
  user_id INT UNSIGNED NOT NULL,
  latitude VARCHAR(50) NOT NULL,
  longitude VARCHAR(50) NOT NULL,
  location VARCHAR(300) NOT NULL,
  title VARCHAR(300) NOT NULL,
  price VARCHAR(50) NOT NULL,
  square_meters VARCHAR(50) NOT NULL,
  description LONGTEXT NOT NULL
);
CREATE TABLE lands_images
(
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  land_id INT NOT NULL,
  url VARCHAR(300) NOT NULL,
  user_id INT NOT NULL,
  file_name VARCHAR(500) NOT NULL,
  temp_id VARCHAR(64)
);
CREATE TABLE users
(
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(150) NOT NULL,
  password VARCHAR(100) NOT NULL
);
CREATE INDEX user_id ON lands (user_id);
